### ISSUE TITLE
Add services to parse/visualize the logs of the webserver

### ISSUE THREAD

**Issue by doublebyte1** [byteroad/ogcapi-simple#2]
Some ideas:
https://grafana.com/
https://www.elastic.co/elastic-stack
https://www.nagios.org/

**Comment by doublebyte1** [comment]
The beginning of an implementation with ELK: https://github.com/byteroad/ogcapi-simple/tree/elk

**Comment by PascalLike** [comment]
Another FOSS option: https://www.fluentd.org/ (but I guess will need Grafana anyway for this)

**Comment by PascalLike** [comment]
Added implementation with matomo here: https://github.com/byteroad/ogcapi-simple/tree/matomo

Matomo is an open alternative to Google Analytics. It works best on websites where you can inject a javascript script, but it can also provide statistics by processing logs from a web server like Apache and Nginx. Obviously in this case the statistics are limited to log information, so the number of accesses by URL. This type of information should be enough because it must be used with pygeoapi, which is a REST API.
